name: pint

on:
  push:
    paths:
      - '**.php'
    branches:
      - '!staging'
      - '!production'
  pull_request:
    paths:
      - '**.php'
    branches:
      - '!staging'
      - '!production'

permissions:
  contents: write

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Pint
        uses: aglipanci/laravel-pint-action@2.4

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: fixed code style'
          commit_options: '--no-verify'
