services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - APP_ENV=${APP_ENV:-production}
        - WWWUID=${UID:-1000}
        - WWWGID=${GID:-1000}
    image: %@VENDOR@%/%@APP_SLUG@%
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      - ".:/var/www/html"
      - "~/.ssh:/var/www/.ssh"
    networks:
      - %@APP_SLUG@%
    depends_on:
      - db
      - mailpit
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  db: 
    %@DOCKERCOMPOSE_DB@%

  mailpit:
    image: "axllent/mailpit:latest"
    restart: unless-stopped
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - %@APP_SLUG@%

networks:
  %@APP_SLUG@%:
    driver: bridge
volumes:
  %@DB_CONNECTION@%_data:
